#!/bin/bash

# zen0x:summary=Launch a TUI or focus an existing terminal window for it
# zen0x:args=<command> [args...]

APP_ID="org.zen0x.$(basename "$1")"
LAUNCH_COMMAND="zen0x-launch-tui $@"

exec zen0x-launch-or-focus "$APP_ID" "$LAUNCH_COMMAND"
