{
  flake.modules.homeManager.hyprland =
    {
      xdg.configFile."hypr/hyprland.lua".text = ''
        require("monitors")
        require("programs")
        require("autostart")
        require("environment")
        require("look")
        require("layouts")
        require("inputs")
        require("binds")
        require("rules")

        -- Load theme colors (generated by theme engine at activation)
        local ok, colors = pcall(require, "colors")
        if ok and hl.config then
            hl.config({
                general = {
                    col = {
                        active_border = colors.active_border,
                        inactive_border = colors.inactive_border,
                    },
                },
                decoration = {
                    shadow = {
                        color = colors.shadow_color,
                        color_inactive = colors.shadow_inactive_color,
                    },
                },
            })
        end
      '';
    }
;
}
