/* Generated by zen0x — do not edit by hand */
@define-color window_bg_color  {{ semantic.bg }};
@define-color accent_bg_color  {{ semantic.elevated }};
@define-color theme_fg_color   {{ semantic.fg }};
@define-color accent_color     {{ semantic.accent }};
@define-color muted_color      {{ semantic.muted }};
@define-color error_bg_color   {{ semantic.danger }};
@define-color error_fg_color   {{ semantic.bg }};
