# Generated by zen0x theme engine.

theme[main_bg]="{{ semantic.bg }}"
theme[main_fg]="{{ semantic.fg }}"
theme[title]="{{ semantic.fg }}"
theme[hi_fg]="{{ semantic.accent }}"
theme[selected_bg]="{{ semantic.border }}"
theme[selected_fg]="{{ semantic.fg }}"
theme[inactive_fg]="{{ semantic.subtle }}"
theme[graph_text]="{{ semantic.fg }}"
theme[meter_bg]="{{ palette.grey_500 }}"
theme[proc_misc]="{{ semantic.accent }}"
theme[cpu_box]="{{ semantic.border }}"
theme[mem_box]="{{ semantic.border }}"
theme[net_box]="{{ semantic.border }}"
theme[proc_box]="{{ semantic.border }}"
theme[div_line]="{{ semantic.border }}"

theme[temp_start]="{{ semantic.success }}"
theme[temp_mid]="{{ semantic.warning }}"
theme[temp_end]="{{ semantic.danger }}"

theme[cpu_start]="{{ semantic.success }}"
theme[cpu_mid]="{{ semantic.warning }}"
theme[cpu_end]="{{ semantic.danger }}"

theme[free_start]="{{ semantic.danger }}"
theme[free_mid]="{{ semantic.warning }}"
theme[free_end]="{{ semantic.success }}"

theme[cached_start]="{{ palette.blue_light }}"
theme[cached_mid]="{{ palette.teal_light }}"
theme[cached_end]="{{ semantic.success }}"

theme[available_start]="{{ semantic.danger }}"
theme[available_mid]="{{ semantic.warning }}"
theme[available_end]="{{ semantic.success }}"

theme[used_start]="{{ semantic.success }}"
theme[used_mid]="{{ semantic.warning }}"
theme[used_end]="{{ semantic.danger }}"

theme[download_start]="{{ semantic.success }}"
theme[download_mid]="{{ palette.teal_light }}"
theme[download_end]="{{ palette.blue_light }}"

theme[upload_start]="{{ semantic.warning }}"
theme[upload_mid]="{{ palette.orange_light }}"
theme[upload_end]="{{ semantic.danger }}"

theme[process_start]="{{ semantic.success }}"
theme[process_mid]="{{ semantic.warning }}"
theme[process_end]="{{ semantic.danger }}"
