# generated by zen0x-generate-theme — do not edit

export ZEN0X_FZF_COLOR_OPTS="
  --color=fg:{{ semantic.fg }},bg:{{ semantic.bg }},hl:{{ semantic.accent }}
  --color=fg+:{{ semantic.fg }},bg+:{{ semantic.panel_alt }},hl+:{{ semantic.accent }}
  --color=border:{{ semantic.border }},gutter:{{ semantic.bg }},header:{{ semantic.accent_alt }}
  --color=info:{{ semantic.accent_alt }},prompt:{{ semantic.warning }},pointer:{{ semantic.danger }}
  --color=marker:{{ semantic.success }},spinner:{{ semantic.accent }}
"
