/* Generated by zen0x — do not edit by hand */
* {
    bg:           {{ semantic.bg }};
    panel:        {{ semantic.panel }};
    panel-alt:    {{ semantic.panel_alt }};
    fg:           {{ semantic.fg }};
    muted:        {{ semantic.muted }};
    accent:       {{ semantic.accent }};
    danger:       {{ semantic.danger }};

    bg-88:        #{{ semantic.bg | strip_hash }}E0;
    panel-alt-60: #{{ semantic.panel_alt | strip_hash }}99;
    panel-alt-50: #{{ semantic.panel_alt | strip_hash }}80;
    fg-06:        #{{ semantic.fg | strip_hash }}0F;
    fg-82:        #{{ semantic.fg | strip_hash }}D1;
    accent-28:    #{{ semantic.accent | strip_hash }}47;
    accent-16:    #{{ semantic.accent | strip_hash }}29;
    accent-60:    #{{ semantic.accent | strip_hash }}99;
    accent-35:    #{{ semantic.accent | strip_hash }}59;
    bg-99:        #{{ semantic.bg | strip_hash }}FC;
    accent-50:    #{{ semantic.accent | strip_hash }}80;
    accent-70:    #{{ semantic.accent | strip_hash }}B3;
    muted-50:     #{{ semantic.muted | strip_hash }}80;
}
