# Generated by theme engine — do not edit by hand

[server]
style = "{{ env.home }}/.config/swayosd/style.css"
top_margin = 0.85
max_volume = 150
min_brightness = 5
show_percentage = true
keyboard_backlight = true
