/* Generated by theme engine — do not edit by hand */

window#osd {
    background: {{ semantic.bg }};
    color: {{ semantic.fg }};
    border: 2px solid {{ semantic.border }};
    border-radius: 12px;
    padding: 12px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    opacity: 0.6;
}

window#osd #container {
    min-width: 300px;
}

window#osd label#osd_label {
    color: {{ semantic.fg }};
    font-weight: bold;
    font-size: 14px;
}

window#osd progressbar#osd_progressbar trough {
    background: {{ semantic.panel_alt }};
    border-radius: 6px;
    min-height: 8px;
}

window#osd progressbar#osd_progressbar block {
    background: {{ semantic.accent }};
    border-radius: 6px;
    min-height: 8px;
}

window#osd image#osd_icon {
    color: {{ semantic.accent }};
    margin-right: 8px;
}
